### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by mrmc-mc** [isaudits/docker-msfconsole-web#1]
When run script get this error:
```
sudo ./msfconsole-web.sh -U xxx -P xxx -a x.x.x.x -p 55553 -S         
```
```                                                                               
Traceback (most recent call last):
  File "/opt/entrypoint.py", line 75, in <module>
    main()
  File "/opt/entrypoint.py", line 34, in main
    if os.environ.get('MSF_RPC_SSL').lower == 'true':
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by mcjon3z** [comment]
Fixed with https://github.com/isaudits/docker-msfconsole-web/commit/096f2976908141680e4d4d7560695ce0d7734a3c
